/*
** Copyright (c) 2021, Andrew Hopkinson.
** Licensed under the GNU GENERAL PUBLIC LICENSE v 3.0 as shown at https://www.gnu.org/licenses/.
*/

/*
** Ansible bundle generator for the Software & Ansible Provisioning module
** (blueprint phase 3). Given a design and the selected packages, emit a
** self-contained, runnable bundle the operator can apply after `terraform
** apply` — the same download-and-run pattern the app already uses for Terraform
** export. Kept dependency-free (deterministic YAML/string templating) so the
** output diffs cleanly and adds no transitive dependencies.
**
**   requirements.yml  -> the roles to pull (Galaxy names / GitHub src+version)
**   playbook.yml      -> apply each selected role to the host group, with vars
**   inventory.yml     -> a host skeleton from the design's compute instances,
**                        each ansible_host wired to a Terraform IP output var
**   run.sh            -> ansible-galaxy install + ansible-playbook
*/

import { OcdSoftwarePackage } from './OcdSoftwareCatalog'

type ResourceBag = Record<string, any[]> | undefined
interface DesignLike {
    metadata?: { title?: string }
    model?: { oci?: { resources?: ResourceBag } }
}

export interface AnsibleBundle {
    /** filename -> file content. */
    files: Record<string, string>
    /** Host names derived from the design (one per compute instance). */
    hosts: string[]
}

const list = (resources: ResourceBag, key: string): any[] =>
    Array.isArray(resources?.[key]) ? (resources as Record<string, any[]>)[key] : []

/** Sanitise an arbitrary display name into an Ansible/Terraform-safe identifier. */
export function ansibleHostName(displayName: string, index: number): string {
    const cleaned = String(displayName || '')
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9_]+/g, '_')
        .replace(/^_+|_+$/g, '')
    return cleaned || `host_${index + 1}`
}

/** YAML-safe scalar: quote when it isn't a clean bareword/number/bool. */
function yamlScalar(value: unknown): string {
    if (typeof value === 'boolean' || typeof value === 'number') return String(value)
    const s = String(value)
    return /^[A-Za-z0-9_./-]+$/.test(s) ? s : JSON.stringify(s)
}

function renderRequirements(packages: ReadonlyArray<OcdSoftwarePackage>): string {
    const galaxy = packages.filter((p) => p.ansible.source === 'galaxy')
    const github = packages.filter((p) => p.ansible.source === 'github')
    const lines = ['---', 'roles:']
    for (const pkg of galaxy) lines.push(`  - name: ${yamlScalar(pkg.ansible.ref)}`)
    for (const pkg of github) {
        lines.push(`  - src: ${yamlScalar(`https://github.com/${pkg.ansible.ref}`)}`)
        lines.push(`    name: ${yamlScalar(pkg.ansible.role)}`)
    }
    return lines.join('\n') + '\n'
}

function renderPlaybook(packages: ReadonlyArray<OcdSoftwarePackage>): string {
    const lines = ['---', '- name: Provision software', '  hosts: all', '  become: true', '  roles:']
    for (const pkg of packages) {
        const vars = pkg.defaultVars ?? {}
        const varKeys = Object.keys(vars)
        if (varKeys.length === 0) {
            lines.push(`    - role: ${yamlScalar(pkg.ansible.role)}`)
        } else {
            lines.push(`    - role: ${yamlScalar(pkg.ansible.role)}`)
            lines.push('      vars:')
            for (const key of varKeys) lines.push(`        ${key}: ${yamlScalar(vars[key])}`)
        }
    }
    return lines.join('\n') + '\n'
}

function renderInventory(hosts: string[]): string {
    const lines = ['---', 'all:', '  hosts:']
    if (hosts.length === 0) {
        // No instances yet — leave an actionable placeholder, not an empty group.
        lines.push('    # No compute instances in the design. Add instances, then regenerate.')
    }
    for (const host of hosts) {
        lines.push(`    ${host}:`)
        // Wire to a Terraform output so `terraform apply` populates the real IP.
        lines.push(`      ansible_host: "{{ ${host}_public_ip }}"`)
    }
    return lines.join('\n') + '\n'
}

const RUN_SH = `#!/usr/bin/env bash
# Generated by OCI Designer — Software & Ansible Provisioning.
# Run after a successful 'terraform apply' that exports the *_public_ip outputs.
set -euo pipefail
ansible-galaxy install -r requirements.yml
ansible-playbook -i inventory.yml playbook.yml "$@"
`

/**
 * Build the full downloadable Ansible bundle for the selected packages against
 * the design. Returns an empty-roles bundle (still valid) when no packages are
 * selected, so callers can preview without special-casing.
 */
export function buildAnsibleBundle(design: DesignLike, packages: ReadonlyArray<OcdSoftwarePackage>): AnsibleBundle {
    const instances = list(design?.model?.oci?.resources, 'instance')
    const hosts = instances.map((inst, i) => ansibleHostName(inst?.displayName ?? inst?.display_name, i))

    return {
        hosts,
        files: {
            'requirements.yml': renderRequirements(packages),
            'playbook.yml': renderPlaybook(packages),
            'inventory.yml': renderInventory(hosts),
            'run.sh': RUN_SH,
        },
    }
}
