/*
** Copyright (c) 2020, 2024, Oracle and/or its affiliates.
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
*/

/*
** GENERATED by scripts/generate_oci_price_snapshot.py - DO NOT EDIT BY HAND.
**
** Offline fallback list-pricing snapshot for the OCD cost estimator. Values are
** PAY_AS_YOU_GO list prices fetched from the public Oracle Cloud Cost Estimator
** Tools API. Regenerate with:
**     python3 scripts/generate_oci_price_snapshot.py --currencies USD,EUR,GBP,JPY,AUD,CAD
*/

import type { PriceMap } from '@ocd/query/pricing'

export const OCI_PRICE_SNAPSHOT_DATE = '2026-06-03'

export const OCI_PRICE_SNAPSHOT: Record<string, PriceMap> = {
    USD: {
        'B97384': { unitPrice: 0.03, metricName: "OCPU Per Hour", currency: "USD", displayName: "Compute - Standard - E5 - OCPU" },
        'B97385': { unitPrice: 0.002, metricName: "Gigabytes Per Hour", currency: "USD", displayName: "Compute - Standard - E5 - Memory" },
        'B93311': { unitPrice: 0.054, metricName: "OCPU Per Hour", currency: "USD", displayName: "Compute - Optimized - X9 - OCPU" },
        'B93312': { unitPrice: 0.0015, metricName: "Gigabyte Per Hour", currency: "USD", displayName: "Compute - Optimized - X9 - Memory" },
        'B91961': { unitPrice: 0.0255, metricName: "Gigabyte Storage Capacity Per Month", currency: "USD", displayName: "Storage - Block Volume - Storage" },
        'B91962': { unitPrice: 0.0017, metricName: "Performance Units Per Gigabyte Per Month", currency: "USD", displayName: "Storage - Block Volume - Performance Units" },
        'B93030': { unitPrice: 0, metricName: "Load Balancer", currency: "USD", displayName: "Load Balancer Base" },
        'B93031': { unitPrice: 0, metricName: "Mbps Per Hour", currency: "USD", displayName: "Load Balancer Bandwidth" },
        'B91628': { unitPrice: 0, metricName: "Gigabyte Storage Capacity Per Month", currency: "USD", displayName: "Object Storage - Storage" },
        'B91627': { unitPrice: 0, metricName: "10,000 Requests per Month (first 50,000 free)", currency: "USD", displayName: "Object Storage - Requests" },
    },
    EUR: {
        'B97384': { unitPrice: 0.0279, metricName: "OCPU Per Hour", currency: "EUR", displayName: "Compute - Standard - E5 - OCPU" },
        'B97385': { unitPrice: 0.00186, metricName: "Gigabytes Per Hour", currency: "EUR", displayName: "Compute - Standard - E5 - Memory" },
        'B93311': { unitPrice: 0.05022, metricName: "OCPU Per Hour", currency: "EUR", displayName: "Compute - Optimized - X9 - OCPU" },
        'B93312': { unitPrice: 0.001395, metricName: "Gigabyte Per Hour", currency: "EUR", displayName: "Compute - Optimized - X9 - Memory" },
        'B91961': { unitPrice: 0.023715, metricName: "Gigabyte Storage Capacity Per Month", currency: "EUR", displayName: "Storage - Block Volume - Storage" },
        'B91962': { unitPrice: 0.001581, metricName: "Performance Units Per Gigabyte Per Month", currency: "EUR", displayName: "Storage - Block Volume - Performance Units" },
        'B93030': { unitPrice: 0, metricName: "Load Balancer", currency: "EUR", displayName: "Load Balancer Base" },
        'B93031': { unitPrice: 0, metricName: "Mbps Per Hour", currency: "EUR", displayName: "Load Balancer Bandwidth" },
        'B91628': { unitPrice: 0, metricName: "Gigabyte Storage Capacity Per Month", currency: "EUR", displayName: "Object Storage - Storage" },
        'B91627': { unitPrice: 0, metricName: "10,000 Requests per Month (first 50,000 free)", currency: "EUR", displayName: "Object Storage - Requests" },
    },
    GBP: {
        'B97384': { unitPrice: 0.023961, metricName: "OCPU Per Hour", currency: "GBP", displayName: "Compute - Standard - E5 - OCPU" },
        'B97385': { unitPrice: 0.0015974, metricName: "Gigabytes Per Hour", currency: "GBP", displayName: "Compute - Standard - E5 - Memory" },
        'B93311': { unitPrice: 0.0431298, metricName: "OCPU Per Hour", currency: "GBP", displayName: "Compute - Optimized - X9 - OCPU" },
        'B93312': { unitPrice: 0.00119805, metricName: "Gigabyte Per Hour", currency: "GBP", displayName: "Compute - Optimized - X9 - Memory" },
        'B91961': { unitPrice: 0.02036685, metricName: "Gigabyte Storage Capacity Per Month", currency: "GBP", displayName: "Storage - Block Volume - Storage" },
        'B91962': { unitPrice: 0.00135779, metricName: "Performance Units Per Gigabyte Per Month", currency: "GBP", displayName: "Storage - Block Volume - Performance Units" },
        'B93030': { unitPrice: 0, metricName: "Load Balancer", currency: "GBP", displayName: "Load Balancer Base" },
        'B93031': { unitPrice: 0, metricName: "Mbps Per Hour", currency: "GBP", displayName: "Load Balancer Bandwidth" },
        'B91628': { unitPrice: 0, metricName: "Gigabyte Storage Capacity Per Month", currency: "GBP", displayName: "Object Storage - Storage" },
        'B91627': { unitPrice: 0, metricName: "10,000 Requests per Month (first 50,000 free)", currency: "GBP", displayName: "Object Storage - Requests" },
    },
    JPY: {
        'B97384': { unitPrice: 4.65, metricName: "OCPU Per Hour", currency: "JPY", displayName: "Compute - Standard - E5 - OCPU" },
        'B97385': { unitPrice: 0.31, metricName: "Gigabytes Per Hour", currency: "JPY", displayName: "Compute - Standard - E5 - Memory" },
        'B93311': { unitPrice: 8.37, metricName: "OCPU Per Hour", currency: "JPY", displayName: "Compute - Optimized - X9 - OCPU" },
        'B93312': { unitPrice: 0.2325, metricName: "Gigabyte Per Hour", currency: "JPY", displayName: "Compute - Optimized - X9 - Memory" },
        'B91961': { unitPrice: 3.9525, metricName: "Gigabyte Storage Capacity Per Month", currency: "JPY", displayName: "Storage - Block Volume - Storage" },
        'B91962': { unitPrice: 0.2635, metricName: "Performance Units Per Gigabyte Per Month", currency: "JPY", displayName: "Storage - Block Volume - Performance Units" },
        'B93030': { unitPrice: 0, metricName: "Load Balancer", currency: "JPY", displayName: "Load Balancer Base" },
        'B93031': { unitPrice: 0, metricName: "Mbps Per Hour", currency: "JPY", displayName: "Load Balancer Bandwidth" },
        'B91628': { unitPrice: 0, metricName: "Gigabyte Storage Capacity Per Month", currency: "JPY", displayName: "Object Storage - Storage" },
        'B91627': { unitPrice: 0, metricName: "10,000 Requests per Month (first 50,000 free)", currency: "JPY", displayName: "Object Storage - Requests" },
    },
    AUD: {
        'B97384': { unitPrice: 0.045, metricName: "OCPU Per Hour", currency: "AUD", displayName: "Compute - Standard - E5 - OCPU" },
        'B97385': { unitPrice: 0.003, metricName: "Gigabytes Per Hour", currency: "AUD", displayName: "Compute - Standard - E5 - Memory" },
        'B93311': { unitPrice: 0.081, metricName: "OCPU Per Hour", currency: "AUD", displayName: "Compute - Optimized - X9 - OCPU" },
        'B93312': { unitPrice: 0.00225, metricName: "Gigabyte Per Hour", currency: "AUD", displayName: "Compute - Optimized - X9 - Memory" },
        'B91961': { unitPrice: 0.03825, metricName: "Gigabyte Storage Capacity Per Month", currency: "AUD", displayName: "Storage - Block Volume - Storage" },
        'B91962': { unitPrice: 0.00255, metricName: "Performance Units Per Gigabyte Per Month", currency: "AUD", displayName: "Storage - Block Volume - Performance Units" },
        'B93030': { unitPrice: 0, metricName: "Load Balancer", currency: "AUD", displayName: "Load Balancer Base" },
        'B93031': { unitPrice: 0, metricName: "Mbps Per Hour", currency: "AUD", displayName: "Load Balancer Bandwidth" },
        'B91628': { unitPrice: 0, metricName: "Gigabyte Storage Capacity Per Month", currency: "AUD", displayName: "Object Storage - Storage" },
        'B91627': { unitPrice: 0, metricName: "10,000 Requests per Month (first 50,000 free)", currency: "AUD", displayName: "Object Storage - Requests" },
    },
    CAD: {
        'B97384': { unitPrice: 0.039318, metricName: "OCPU Per Hour", currency: "CAD", displayName: "Compute - Standard - E5 - OCPU" },
        'B97385': { unitPrice: 0.0026212, metricName: "Gigabytes Per Hour", currency: "CAD", displayName: "Compute - Standard - E5 - Memory" },
        'B93311': { unitPrice: 0.0707724, metricName: "OCPU Per Hour", currency: "CAD", displayName: "Compute - Optimized - X9 - OCPU" },
        'B93312': { unitPrice: 0.0019659, metricName: "Gigabyte Per Hour", currency: "CAD", displayName: "Compute - Optimized - X9 - Memory" },
        'B91961': { unitPrice: 0.0334203, metricName: "Gigabyte Storage Capacity Per Month", currency: "CAD", displayName: "Storage - Block Volume - Storage" },
        'B91962': { unitPrice: 0.00222802, metricName: "Performance Units Per Gigabyte Per Month", currency: "CAD", displayName: "Storage - Block Volume - Performance Units" },
        'B93030': { unitPrice: 0, metricName: "Load Balancer", currency: "CAD", displayName: "Load Balancer Base" },
        'B93031': { unitPrice: 0, metricName: "Mbps Per Hour", currency: "CAD", displayName: "Load Balancer Bandwidth" },
        'B91628': { unitPrice: 0, metricName: "Gigabyte Storage Capacity Per Month", currency: "CAD", displayName: "Object Storage - Storage" },
        'B91627': { unitPrice: 0, metricName: "10,000 Requests per Month (first 50,000 free)", currency: "CAD", displayName: "Object Storage - Requests" },
    },
}

export const getSnapshotPriceMap = (currency: string): PriceMap => {
    return OCI_PRICE_SNAPSHOT[(currency || 'USD').toUpperCase()] ?? OCI_PRICE_SNAPSHOT.USD ?? {}
}
